namespace CoreApi_BL_App.Models
{
    public class Object9420
    {


        //public Object9420();

        public static string DownloadZipFIle { get; set; }
        public string Image { get; set; }//added by bipin for Oltimo
        public string ModeofPayment { get; set; }
        public string PayMode { get; set; }
        public double Pre_Bal { get; set; }
        public double MN_Amount { get; set; }
        public double OldUpgrade_Amount { get; set; }
        public string Details { get; set; }
        public double Upgrade_Amount { get; set; }
        public double N_Amount { get; set; }
        public double Offer_Vat { get; set; }
        public double Offer_ServiceTax { get; set; }
        public double AMC_Vat { get; set; }
        public double AMC_ServiceTax { get; set; }
        public double Label_Vat { get; set; }
        public string Upgrade_From { get; set; }
        public string FileType { get; set; }
        public string Amt_Type { get; set; }
        public int Pay_Type { get; set; }
        public string LabelRequestID { get; set; }
        public string Label_Code { get; set; }
        public string LabelUploadRptID { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_ID { get; set; }
        public string Category_Name { get; set; }
        public string Category_ID { get; set; }
        public string User_Type { get; set; }
        public string User_ID { get; set; }
        public double MDiscount { get; set; }
        public double CDiscount { get; set; }
        public double Discount { get; set; }
        public double OldReqAmt { get; set; }
        public double OldPayAmt { get; set; }
        public double PayAmt { get; set; }
        public double Label_ServiceTax { get; set; }
        public string TaxSet_ID { get; set; }
        public double MVat_Tax_Value { get; set; }
        public double MService_Tax_Value { get; set; }
        public double Rate { get; set; }
        public double Qty { get; set; }
        public string Admin_Remarks { get; set; }
        public string Comment_Txt { get; set; }
        public string Message { get; set; }
        public string AmcOfferRemarks { get; set; }
        public double Rec_Payment { get; set; }
        public string Location { get; set; }
        public string Request_No { get; set; }
        public double Net_Pay { get; set; }
        public string Net_Balance { get; set; }
        public DateTime Last_Paid_Date { get; set; }
        public double Last_Paid_Amount { get; set; }
        public string Last_Payment_Receipt { get; set; }
        public string Remarks { get; set; }
        public string Label_Name { get; set; }
        public double ManuReq_Payment { get; set; }
        public double Credit_Payment { get; set; }
        public double Vat_Tax_Value { get; set; }
        public double Service_Tax_Value { get; set; }
        public double Vat_Tax { get; set; }
        public double Service_Tax { get; set; }
        public double Tax { get; set; }
        public double G_Amount { get; set; }
        public double Debit_Payment { get; set; }
        public double MG_Amount { get; set; }
        public double TReq_Payment { get; set; }
        public double TRec_Payment { get; set; }
        public string TransRow_ID { get; set; }
        public double TotalReq_Payment { get; set; }
        public double Req_Payment { get; set; }
        public double AdminReq_Payment { get; set; }
        public string Refund_From { get; set; }
        public string Label_Size { get; set; }
        public double Label_Prise { get; set; }
        public string Label_Width { get; set; }
        public string RTGS_Code { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string UPIID { get; set; }
        public string Pincode { get; set; }
        public string IFSC_Code { get; set; }
        public string Branch { get; set; }
        public string Account_No { get; set; }
        public string Account_HolderNm { get; set; }
        public string Account_Type { get; set; }
        public string Bank_Name { get; set; }
        public int TotalTime { get; set; }
        public int Time_Days { get; set; }
        public double Promo_AmountA { get; set; }
        public double Promo_Amount { get; set; }
        public string Promo_Name { get; set; }
        public string OldPromo_Id { get; set; }
        public string Bank_ID { get; set; }
        public string Promo_Id { get; set; }
        public string chkpassbook { get; set; }
        public string Courier_ID { get; set; }
        public string Series_From { get; set; }
        public int Courier_Status { get; set; }
        public string chkstr { get; set; }
        public string Dispatch_Location { get; set; }
        public long BatchSize { get; set; }
        public string Dispatch_Pin { get; set; }
        public int CourierPkid { get; set; }
        public DateTime Expected_Date { get; set; }
        public string Tracking_No { get; set; }
        public string Courier_Disp_ID { get; set; }
        public string Courier_Address { get; set; }
        public string Courier_Mobile { get; set; }
        public string Courier_Email { get; set; }
        public string Courier_Name { get; set; }
        public DateTime Dispatch_Date { get; set; }
        public string Cancelled_By { get; set; }
        public string UniqueID { get; set; }
        public string TransType { get; set; }
        public int Plan_days { get; set; }
        public int Plan_months { get; set; }
        public int Plan_year { get; set; }
        public int Plan_Time { get; set; }
        public string OldPlan_ID { get; set; }
        public string Plan_ID { get; set; }
        public string Plan_Name { get; set; }
        public int Doc_Flag { get; set; }
        public string Label_Msg { get; set; }
        public int Disp { get; set; }
        public int Flag { get; set; }
        public string Msg { get; set; }
        public string Label_Image { get; set; }
        public string Label_Height { get; set; }
        public string Pro_Doc { get; set; }
        public string Manage_By { get; set; }
        public string Plan_Type { get; set; }
        public double Plan_Amount { get; set; }
        public string Trans_Type { get; set; }
        public string Manu_Remark { get; set; }
        public string Admin_Remark { get; set; }
        public string Amt_Remark { get; set; }
        public double AmcPlan_Amount { get; set; }
        public int Amc_Offer_ID { get; set; }
        public double PlanAmount { get; set; }
        public double Pay_Balance { get; set; }
        public double Balance { get; set; }
        public double Manu_Balance { get; set; }
        public double Admin_Balance { get; set; }
        public double Plan_DiscountC { get; set; }
        public double Plan_Discount { get; set; }
        public double Plan_AmountA { get; set; }
        public double Availabl_Balance { get; set; }
        public string Head_Name { get; set; }
        public string Head_ID { get; set; }
        public string Invoice_ID { get; set; }
        public int IsRetailer { get; set; }
        public string oldPassword { get; set; }
        public string Password { get; set; }
        public DateTime Rec_Date { get; set; }
        public DateTime Req_Date { get; set; }
        public string Reg_Date { get; set; }
        public int Status { get; set; }
        public string Fax { get; set; }
        public string Mobile_No { get; set; }
        public string Contact_Person { get; set; }
        public long intM_Consumer_MCOde { get; set; }
        public int M_ConsumerID { get; set; }
        public int City_ID { get; set; }
        public string Address { get; set; }
        public string Phone_No { get; set; }
        public string WebSite { get; set; }
        public int Email_Vari_Flag { get; set; }
        public string TypeOfCompany { get; set; }
        public long Code1 { get; set; }
        public string Gen_By { get; set; }
        public string Gen_Date { get; set; }
        public string logo_path { get; set; }
        public DateTime PromoDateTo { get; set; }
        public DateTime PromoDateFrom { get; set; }
        public int Update_Flag { get; set; }
        public DateTime DateToChk { get; set; }
        public DateTime DateTo { get; set; }
        public DateTime DateFrom { get; set; }
        public DateTime AmcDateTo { get; set; }
        public DateTime AmcDateFrom { get; set; }
        public string Condition { get; set; }
        public string Comp_type { get; set; }
        public DateTime DateFromChk { get; set; }
        public long Code2 { get; set; }
        public string PacketCode { get; set; }
        public int Comp_Cat_Id { get; set; }
        public string Email { get; set; }
        public string cmobile { get; set; }
        public string Name { get; set; }
        public string PartmerID { get; set; }
        public int DocFlag { get; set; }
        public string Doc_Id { get; set; }
        public string PANNo { get; set; }
        public string Signature { get; set; }
        public string Comp_Addressproof { get; set; }
        public string VAT { get; set; }
        public string PAN_TAN { get; set; }
        public string Comp_Info { get; set; }
        public string dealer_mobile { get; set; }
        public string dealerid { get; set; }
        public string Owner_proof { get; set; }
        public string Comp_Email { get; set; }
        public string PANNoProof { get; set; }
        public string Addproof { get; set; }
        public string Comp_Name { get; set; }
        public string Comp_ID { get; set; }
        public int ActNoofCodes { get; set; }
        public int ExcNoofCodes { get; set; }
        public string Channels { get; set; }
        public string ProductionUnit { get; set; }
        public string IDProof { get; set; }
        public int NoofCodes { get; set; }
        public long M_code_Row_ID { get; set; }
        public string Row_ID { get; set; }
        public string EnglishFle { get; set; }
        public string HindiFile { get; set; }
        public string BankAccNo { get; set; }
        public string Photo { get; set; }
        public string OldRow_ID { get; set; }
        public string Series_DFrom { get; set; }
        public string Use_Type { get; set; }
        public int Print_Status { get; set; }
        public string NewsContent { get; set; }
        public string NewsSubject { get; set; }
        public string NewsLetterID { get; set; }
        public string Comments { get; set; }
        public DateTime Entry_Date { get; set; }
        public string Batch_No { get; set; }
        public string Send_To { get; set; }
        public string Exp_Date { get; set; }
        public DateTime Mfd_Date { get; set; }
        public int Warranty { get; set; }
        public double MRP { get; set; }
        public string Path { get; set; }
        public string statusstr { get; set; }
        public string modestr { get; set; }
        public string DemoMfd_Date { get; set; }
        public string datetostr { get; set; }
        public string Send_CC { get; set; }
        public string Send_Subject { get; set; }
        public DateTime Invoice_Date { get; set; }
        public string Invoice_No { get; set; }
        public string Testimonial_Text { get; set; }
        public string Testimonial_ID { get; set; }
        public string Img2 { get; set; }
        public string Img1 { get; set; }
        public string Send_BCC { get; set; }
        public int Del_Flag { get; set; }
        public int Act_Flag { get; set; }
        public string ImgFolderPath { get; set; }
        public string FolderPath { get; set; }
        public string Packet_Name { get; set; }
        public string Send_AttachFile { get; set; }
        public string Send_Message { get; set; }
        public int Con_Flag { get; set; }
        public DateTime Allot_Date { get; set; }
        public string datefromstr { get; set; }
        public string Pro_Descri { get; set; }
        public DateTime Enq_Date { get; set; }
        public string Dial_Mode { get; set; }
        public string Retailer_Name { get; set; }
        public long intFlag { get; set; }
        public long Norec { get; set; }
        public long u2 { get; set; }
        public long l2 { get; set; }
        public string Mode_Detail { get; set; }
        public long u1 { get; set; }
        public int Series_SerialTo { get; set; }
        public int Series_Serial { get; set; }
        public int Series_Order { get; set; }
        public int ScrapeFlag { get; set; }
        public int Use_Count { get; set; }
        public DateTime Print_Date { get; set; }
        public long l1 { get; set; }
        public string DML { get; set; }
        public string callercircle { get; set; }
        public DateTime callerdate { get; set; }
        public string Pro_Name { get; set; }
        public string Pro_Entry_Date { get; set; }
        public string Service_ID { get; set; }
        public string Pro_ID { get; set; }
        public string Subscribe_Id { get; set; }
        public string designation { get; set; }
        public string network { get; set; }
        public string consumer_name { get; set; }
        public string TempleteHead { get; set; }
        public string M_Code { get; set; }
        public int Is_Success { get; set; }
        public string Received_Code2 { get; set; }
        public string Received_Code1 { get; set; }
        public string callertime { get; set; }
        public string SubHeadId { get; set; }
        public string Series_To { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public string Headmechanicmobilenumber { get; set; }
        public string Paymentmode { get; set; }
    }
}
